<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-05-29T23:37:32 PET" name="Suite" finished-at="2023-05-29T23:38:11 PET" duration-ms="38958">
    <groups>
    </groups>
    <test started-at="2023-05-29T23:37:32 PET" name="Test" finished-at="2023-05-29T23:38:11 PET" duration-ms="38958">
      <class name="main">
        <test-method is-config="true" signature="SetUp()[pri:0, instance:main@1583741e]" started-at="2023-05-29T23:37:32 PET" name="SetUp" finished-at="2023-05-29T23:37:41 PET" duration-ms="8936" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUp -->
        <test-method signature="emptyCart()[pri:0, instance:main@1583741e]" started-at="2023-05-29T23:37:41 PET" name="emptyCart" finished-at="2023-05-29T23:37:52 PET" duration-ms="11608" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- emptyCart -->
        <test-method is-config="true" signature="TearDown()[pri:0, instance:main@1583741e]" started-at="2023-05-29T23:37:52 PET" name="TearDown" finished-at="2023-05-29T23:37:52 PET" duration-ms="117" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
        <test-method is-config="true" signature="SetUp()[pri:0, instance:main@1583741e]" started-at="2023-05-29T23:37:52 PET" name="SetUp" finished-at="2023-05-29T23:37:58 PET" duration-ms="5842" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUp -->
        <test-method signature="fillCart()[pri:0, instance:main@1583741e]" started-at="2023-05-29T23:37:58 PET" name="fillCart" finished-at="2023-05-29T23:38:10 PET" duration-ms="11951" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Protein total sum does not match expected [2.73] but found [1.0]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Protein total sum does not match expected [2.73] but found [1.0]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEquals(Assert.java:774)
at main.fillCart(main.java:43)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- fillCart -->
        <test-method is-config="true" signature="TearDown()[pri:0, instance:main@1583741e]" started-at="2023-05-29T23:38:10 PET" name="TearDown" finished-at="2023-05-29T23:38:11 PET" duration-ms="116" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
      </class> <!-- main -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
